"""empty message

Revision ID: 58782256bdc6
Revises: 7f5cb2113880
Create Date: 2020-12-18 20:20:54.233133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58782256bdc6'
down_revision = '7f5cb2113880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
