"""empty message

Revision ID: dcc0a5767574
Revises: 9787c2718f96
Create Date: 2020-12-18 18:27:56.095265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc0a5767574'
down_revision = '9787c2718f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time_o', sa.String(), nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time_o')
    # ### end Alembic commands ###
